apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - image: postgres
          imagePullPolicy: Always
          ports:
          - containerPort: 5432
          name: db
          env: 
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
        - image: {{ .Values.app.ecr_uri }}:{{ .Values.app.image_tag }}
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.app.port.containerPort }}
          name: {{ .Values.app.name }}
          envFrom:
          - configMapRef:
                name: {{ .Values.app.name }}