apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  ports:
  - port: {{ .Values.app.port.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.app.port.containerPort }}
  selector:
    app: {{ .Values.app.name }}